### ISSUE TITLE
Not working with http://  trying to force https://

### ISSUE THREAD

**Issue by kilroy59** [w3c/i18n-checker#79]

**Comment by kilroy59** [comment]
Can't find site which is up. Fairly sure it's forcing https:// which doesn't exist for site I'm testing.

**Comment by r12a** [comment]
@kilroy59 Thanks for the report. I'll pass it on to the systems team, however, it would help a lot if you could indicate which page you were trying to test.

**Comment by kilroy59** [comment]
r12a  I tried two different sites. First the one I wanted to test. http://www.imawww.com/ 
and then to verify it was the checker and not the site,  http://www.turvill.com/
In both cases it returns the site with a https prefix and an unreachable message. All the https sites I tested worked fine.

**Comment by gosko** [comment]
I committed a fix but it is not yet deployed on our site. Hopefully will be deployed by tomorrow.

**Comment by r12a** [comment]
@gosko what's the status on this?  The checker still doesn't find  http://www.imawww.com/

**Comment by gosko** [comment]
@r12a @kilroy59 I believe this should now be deployed on our servers, could you please confirm it is working as expected?

**Comment by r12a** [comment]
@gosko  Doesn't appear to be.  I go to https://validator.w3.org/i18n-checker/ add www.imawww.com to the input field, and get the same problem. And the text in the input field is changed to https://www.imawww.com/  (and yes, i did a shift-reload of the page first).

**Comment by kilroy59** [comment]
Just checked and http://www.imawww.com/ still changes to https://www.imawww.com/ and is unreachable.

**Comment by gosko** [comment]
@kilroy59 Yes, confirmed, sorry. Maybe one of our two backend servers is still out of date. I will investigate further.

**Comment by gosko** [comment]
@kilroy59 @r12a I think this should finally be fixed for real. One of the resources was being served from a cache. I don't understand how it worked for me when I was testing yesterday – maybe my browser had a cached version from when I was debugging last month.

**Comment by kilroy59** [comment]
Yes, finally! Thank you for your hard work. Now, time for me to add a language attribute to the html tag :)

**Comment by xfq** [comment]
Confirmed. Closing.
